- name: Create a VM from latest template
  hosts: localhost
  gather_facts: no
  vars_files:
    - variable/variable.yml
    - variable/credentials.yml
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ test_vm }}"
      template: "{{ vm_name_template }}"
      datacenter: "{{ vmware_datacenter }}"
      folder: "{{ vmware_folder }}"
      state: poweredoff
      is_template: No
      cluster: "{{ vmware_cluster }}"
      wait_for_ip_address: no

