pipelines:
  NPN-Win2k16-Template-Patching:
#    secure_variables:
#      ENV_PASSWORD: "AES:Npay3ETiC8Pw4NqvQBkhvw==:zOEXbIw0iMhUDF4ROghavQ=="
    
    group: Template-Patching
    materials:
      infracode:
        git: git@githuben.intranet.mckinsey.com:himanshu-sharma-xft/template-patching-npn-2k16.git
        branch: master
        auto_update: true
        blacklist:
        - "README.md"
        timer:
          spec: "0 15 1 ? * *"
    stages:
      - Update-Template:
          clean_workspace: true
          jobs:
            Update-Template:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - final_code.yaml
      - Deploy-test-VM:
          clean_workspace: true
          jobs:
            Deploy-test-VM:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - deploy-test-vm.yaml
      - Final_Cleanup:
          clean_workspace: true
          jobs:
            rename_templates:
              resources:
                - linux          
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - rename-templates.yaml


