pipelines:
   NPN-Win2k16-Template-Patching:
    environment_variables:
      ENV_USER: "{{SECRET:[npn2k16][ENV_USER]}}"
      ENV_PASSWORD: "{{SECRET:[npn2k16][ENV_PASS]}}"
    group: Windows-Template-Patching
    timer:
      spec: "0 0 3 ? * SUN"
      only_on_changes: no
    materials:
      infracode:
        git: git@githuben.intranet.mckinsey.com:himanshu-sharma-xft/template-patching-npn-2k16.git
        branch: master
        auto_update: true
        blacklist:
        - "README.md"
    stages:
      - Update-Template:
          clean_workspace: true
          jobs:
            Update-Template:          
              resources:
                - linux
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ansible-playbook final_code.yaml -e VMWARE_USER=$ENV_USER -e VMWARE_PASSWORD=$ENV_PASSWORD           
      - Deploy-test-VM:
          clean_workspace: true
          jobs:
            Deploy-test-VM:          
              resources:
                - linux
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ansible-playbook deploy-test-vm.yaml -e VMWARE_USER=$ENV_USER -e VMWARE_PASSWORD=$ENV_PASSWORD
      - Final_Cleanup:
          clean_workspace: true
          jobs:
            rename_templates:
              resources:
                - linux          
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ansible-playbook rename-templates.yaml -e VMWARE_USER=$ENV_USER -e VMWARE_PASSWORD=$ENV_PASSWORD
