- name: Rename virtual machine from old name to new name using UUID
  gather_facts: no
  vars_files:
    - variable/variable.yml
    - variable/credentials.yml

  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "{{ vmware_template }}"
        datacenter: "{{ vmware_datacenter }}"
        cluster_name: "{{ vmware_cluster }}"

    - name: Get VM "{{ vmware_template }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        datacenter: "{{ vmware_datacenter }}"
        folder: "{{ vmware_folder }}"
        name: "{{ vmware_template }}"
      register: vm_facts

    - name: Rename "{{ vmware_template }}" to "{{ bkp_template }}"
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        state: present
        is_template: True
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ bkp_template }}"

- name: Rename virtual machine from old name to new name using UUID
  gather_facts: no
  vars_files:
    - variable/variable.yml
    - variable/credentials.yml
  hosts: localhost

  tasks:
    - set_fact:
        vm_name: "{{ vm_name_template }}"
        datacenter: "{{ vmware_datacenter }}"
        cluster_name: "{{ vmware_cluster }}"

    - name: Get VM "{{ vmware_template }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        datacenter: "{{ vmware_datacenter }}"
        folder: "{{ vmware_folder }}"
        name: "{{ vm_name_template }}"
      register: vm_facts

    - name: Rename "{{ vm_name_template }}" to "{{ vmware_template }}"
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        state: present
        is_template: True
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ vmware_template }}"
        
    - name: Send the final communication to MIS Wintel team about the sucessfull patching of the template "{{ vmware_template }}"
      mail:
        host: localhost
        port: 25
        from: ankit_sinha-ggn@mckinsey.com
        subject: AMDC-NPN-Vcenter Win2016-Template|successfully patched '{{ vmware_template }}'
        body: AMDC-NPN vcenter "{{ vmware_template }}" has been successfully patched and rebooted via GOCD pipeline.
        to:
        - mis-wintel@mckinsey.com


